# The default config file for danmuku

# enable danmuku script or not, <yes|no>
enable=yes

# binding key for Loader:toggle()
toggle_key_binding=b

# commands path directories, like PATH, seperated by a ':'
bin_path=~~home/danmuku-data/bin/:~/.local/bin/:/usr/bin/

# cache directory for danmuku XML files and ass files
# also need subdir for different websites:
#   'bilibili' for B站, 'mgtv' for 芒果TV, 'qq' for 腾讯视频,
#   'youku' for 优酷, 'iqiyi' for 爱奇艺, 'gamer' for 巴哈姆特
# default: ~/.config/mpv/danmuku-data/cache/
#cache_dir = '~~home/danmuku-data/cache/

# other settings for ass， used by convert commands above
# width and height, like 1920x1080 or 'auto'
resolution=auto
# Reserve blank on the bottom of the stage, 0.0-1.0
reserve=0.2
# fontname of general danmaku
#fontname=Microsoft YaHei
fontsize=50.0
# opacity of danmaku, 0.0-1.0
alpha=0.95
# Duration of scrolling comment display
duration_marquee=10.0
# Duration of still comment display
duration_still=5.0
# Regular expressions from file (one line one regex) to filter comments
filter_file=~~home/danmuku-data/share/BBL.txt
